import * as Sequelize from 'sequelize';

export interface IProcessTokenAttributes {
  type: string;
  payload: string;
  flowNodeInstanceId: string;
  // This column is auto-generated by Sequelize.
  // To avoid having to declare it manually, but to still be able to use it
  // internally, it is marked as optional here.
  createdAt?: Date;
}

export type ProcessToken = Sequelize.Instance<IProcessTokenAttributes> & IProcessTokenAttributes;

export function defineProcessToken(sequelize: Sequelize.Sequelize): Sequelize.Model<ProcessToken, IProcessTokenAttributes> {
  const attributes: SequelizeAttributes<IProcessTokenAttributes> = {
    type: {
      type: Sequelize.STRING,
      allowNull: true,
    },
    payload: {
      // NOTE: Use Sequelize.TEXT, since payloads can contain all kinds of things and could therefore exceed 255 chars.
      type: Sequelize.TEXT,
      allowNull: true,
    },
    flowNodeInstanceId: {
      type: Sequelize.STRING,
      allowNull: false,
    },
  };

  // TODO: Rename to `ProcessToken`, once the old datamodel with the same name is removed.
  return sequelize.define<ProcessToken, IProcessTokenAttributes>('ProcessToken', attributes);
}
